# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/Zynq_CPU_system_ila_0_2.xci
# IP: The module: 'Zynq_CPU_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/bd_180d.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_180d || ORIG_REF_NAME==bd_180d} -quiet] -quiet

# IP: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/bd_180d_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_180d_ila_lib_0 || ORIG_REF_NAME==bd_180d_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_180d_ila_lib_0 || ORIG_REF_NAME==bd_180d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_180d_ila_lib_0 || ORIG_REF_NAME==bd_180d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/bd_180d_ila_lib_0_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/bd_180d_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/Zynq_CPU_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/Zynq_CPU_system_ila_0_2.xci
# IP: The module: 'Zynq_CPU_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/bd_180d.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_180d || ORIG_REF_NAME==bd_180d} -quiet] -quiet

# IP: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/bd_180d_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_180d_ila_lib_0 || ORIG_REF_NAME==bd_180d_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_180d_ila_lib_0 || ORIG_REF_NAME==bd_180d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_180d_ila_lib_0 || ORIG_REF_NAME==bd_180d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/ip/ip_0/bd_180d_ila_lib_0_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/bd_0/bd_180d_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_0_2/Zynq_CPU_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
