# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_processing_system7_0_0/Zynq_CPU_processing_system7_0_0.xci
# IP: The module: 'Zynq_CPU_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_processing_system7_0_0/Zynq_CPU_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_processing_system7_0_0/Zynq_CPU_processing_system7_0_0.xci
# IP: The module: 'Zynq_CPU_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_processing_system7_0_0/Zynq_CPU_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
