@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 01 20:09:18 -0400 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_ddpuf_spi_behav -key {Behavioral:sim_2:Functional:tb_ddpuf_spi} -tclbatch tb_ddpuf_spi.tcl -protoinst "protoinst_files/bd_d98c.protoinst" -protoinst "protoinst_files/bd_d89c.protoinst" -protoinst "protoinst_files/bd_d91c.protoinst" -protoinst "protoinst_files/Zynq_CPU.protoinst" -view C:/Users/auste/FPGA_Projects/DDPUF_SPI/tb_ddpuf_spi_behav_success.wcfg -log simulate.log"
call xsim  tb_ddpuf_spi_behav -key {Behavioral:sim_2:Functional:tb_ddpuf_spi} -tclbatch tb_ddpuf_spi.tcl -protoinst "protoinst_files/bd_d98c.protoinst" -protoinst "protoinst_files/bd_d89c.protoinst" -protoinst "protoinst_files/bd_d91c.protoinst" -protoinst "protoinst_files/Zynq_CPU.protoinst" -view C:/Users/auste/FPGA_Projects/DDPUF_SPI/tb_ddpuf_spi_behav_success.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
