# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/Zynq_CPU_system_ila_1_1.xci
# IP: The module: 'Zynq_CPU_system_ila_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/bd_d91c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d91c || ORIG_REF_NAME==bd_d91c} -quiet] -quiet

# IP: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/bd_d91c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d91c_ila_lib_0 || ORIG_REF_NAME==bd_d91c_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d91c_ila_lib_0 || ORIG_REF_NAME==bd_d91c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d91c_ila_lib_0 || ORIG_REF_NAME==bd_d91c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/bd_d91c_ila_lib_0_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/bd_d91c_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/Zynq_CPU_system_ila_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_system_ila_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/Zynq_CPU_system_ila_1_1.xci
# IP: The module: 'Zynq_CPU_system_ila_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/bd_d91c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d91c || ORIG_REF_NAME==bd_d91c} -quiet] -quiet

# IP: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/bd_d91c_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d91c_ila_lib_0 || ORIG_REF_NAME==bd_d91c_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d91c_ila_lib_0 || ORIG_REF_NAME==bd_d91c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d91c_ila_lib_0 || ORIG_REF_NAME==bd_d91c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/ip/ip_0/bd_d91c_ila_lib_0_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/bd_0/bd_d91c_ooc.xdc

# XDC: c:/Users/auste/FPGA_Projects/DDPUF_SPI/DDPUF_SPI.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_system_ila_1_1/Zynq_CPU_system_ila_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_system_ila_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
